### DISCUSSION TITLE
v2.7

### DISCUSSION THREAD

**Discussion by tomsun28** [dromara/issues-translate-action#76] [General]
#### What's Changed
* chore: upgrade node.js version by @chenquan in https://github.com/usthe/issues-translate-action/pull/72
* upgrade dependencies by @tomsun28 in https://github.com/usthe/issues-translate-action/pull/75

#### Use    

````  
name: 'issue-translator'
on: 
  issue_comment: 
    types: [created]
  issues: 
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: usthe/issues-translate-action@v2.7
````

<hr /><em>This discussion was created from the release <a href='https://github.com/usthe/issues-translate-action/releases/tag/v2.7'>v2.7</a>.</em>
