### ISSUE TITLE
I want to use my own bot

### ISSUE THREAD

**Issue by yizhihenpidehou** [dromara/issues-translate-action#90]
I did not make sure that I have generated correct token in my bot account. Could you please give me some help, because GitHub workflow give me following error message:

Resource not accessible by personal access token

**Comment by tomsun28** [comment]
hi please follow this

1. Create a new github account as your bot
2. Use the account to generate a new token as BOT_GITHUB_TOKEN
3. Add the Secrets BOT_GITHUB_TOKEN = ${token} in your project

**And make sure your github bot account has permission to access the repository**

**Comment by yizhihenpidehou** [comment]
Thanks for your reply. I try to invite my bot account to my repo and give him Triage role, but I still fail to achieve it. T T

**Comment by yizhihenpidehou** [comment]
Above question is done. But I have another question! I wonder if I can remove the hint in the response such as :
Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿

**Comment by tomsun28** [comment]
by config CUSTOM_BOT_NOTE

```
    steps:
      - uses: usthe/issues-translate-action@v2.7
        with:
          CUSTOM_BOT_NOTE: Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
          # not require. Customize the translation robot prefix message.
```
